declare enum MeasurementTypeKey {
  bloodOxygen = 'spo2',
  distance = 'distance',
  bloodPressure = 'blood-pressure',
  bloodOxygenPulseRate = 'blood-oxygen-pulse-rate',
  bloodGlucose = 'blood-glucose',
  triglycerides = 'triglycerides',
  uricAcid = 'uric-acid',
  ketone = 'ketone',
  lactate = 'lactate',
  cholesterol = 'cholesterol',
  temperature = 'body-temperature',
  ecg = 'ecg',
  ecgHeartRate = 'ecg-heart-rate',
  ecgHRV = 'ecg-hrv',
  bloodPressureDiastolic = 'blood-pressure-diastolic',
  bloodPressureSystolic = 'blood-pressure-systolic',
  bloodPressureHeartRate = 'blood-pressure-heartRate',
  heartRate = 'heartRate',
  bodyWeight = 'body-weight',
  bodyHeight = 'body-height',
  gratitude = 'gratitude',
  mood = 'mood',
  steps = 'steps',
  burnedCalories = 'burned-calories',
  dailySteps = 'daily-steps',
  questionnaire = 'questionnaire',
}

export default MeasurementTypeKey;
